version: '3'

services:
  db:
    image: postgres:15beta1-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/db
    volumes:
      - /var/run/postgresql
