[package]
name = "dbcop"
version = "0.1.0"
authors = ["Ranadeep Biswas <ranadip.bswas@gmail.com>"]

[dependencies]
mysql = "*"
postgres = "*"
rand = "*"
clap = "*"
ansi_term = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
byteorder = "*"
petgraph = "*"
antidotedb = { path = "../antidotedb" }

[profile.release]
opt-level = 3
