[package]
name = "dbcop"
version = "0.1.0"
authors = ["Ranadeep Biswas <ranadip.bswas@gmail.com>"]

[dependencies]
rand = "0.7.2"
clap = "2.33.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.44"
serde_yaml = "0.8.11"
byteorder = "1.3.2"
rayon = "1.2.1"
slog = "2.5.2"
slog-term = "2.4.2"
slog-json = "2.3.0"
chrono = { version = "0.4.10", features = ["serde"] }
bincode = "1.2.1"

[dev-dependencies]
nom = "5.0.1"
mysql = "17.0.0"
postgres = "0.17.0-alpha.2"
mongodb = "0.4.0"
antidotedb = { git = "https://github.com/rnbguy/antidotedb_rs" }

[profile.release]
opt-level = 3
