version:              '3'
services:
  n1:
    image:            erkules/galera
    container_name:   dbcop-n1
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://"]
    hostname:         n1
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.11
  n2:
    image:            erkules/galera
    container_name:   dbcop-n2
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://n1"]
    links:            [n1]
    hostname:         n2
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.12
  n3:
    image:            erkules/galera
    container_name:   dbcop-n3
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://n1"]
    links:            [n1]
    hostname:         n3
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.13
  n4:
    image:            erkules/galera
    container_name:   dbcop-n4
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://n1"]
    links:            [n1]
    hostname:         n4
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.14
  n5:
    image:            erkules/galera
    container_name:   dbcop-n5
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://n1"]
    links:            [n1]
    hostname:         n5
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.15
  n6:
    image:            erkules/galera
    container_name:   dbcop-n6
    command:          ["--wsrep-cluster-name=local-test", "--wsrep-cluster-address=gcomm://n1"]
    links:            [n1]
    hostname:         n6
    networks:
      dbcop-net:
        ipv4_address: 172.18.0.16


networks:
  dbcop-net:
    driver:           bridge
    ipam:
     config:
       - subnet:      172.18.0.0/16
