version: '3'

services:
  yb-master-0:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-master"
        - "--fs_data_dirs=/mnt/master"
        - "--master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
        - "--rpc_bind_addresses=yb-master-0:7100"
        - "--replication_factor=2"
      ports:
        - "127.0.0.1:7000:7000"
  yb-master-1:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-master"
        - "--fs_data_dirs=/mnt/master"
        - "--master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
        - "--rpc_bind_addresses=yb-master-1:7100"
        - "--replication_factor=2"
  yb-master-2:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-master"
        - "--fs_data_dirs=/mnt/master"
        - "--master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
        - "--rpc_bind_addresses=yb-master-2:7100"
        - "--replication_factor=2"
  yb-tserver-0:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-tserver"
        - "--fs_data_dirs=/mnt/tserver"
        - "--start_pgsql_proxy"
        - "--rpc_bind_addresses=yb-tserver-0:9100"
        - "--tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
      ports:
        - "127.0.0.1:5433:5433"
        - "127.0.0.1:9000:9000"
      depends_on:
        - yb-master-0
  yb-tserver-1:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-tserver"
        - "--fs_data_dirs=/mnt/tserver"
        - "--start_pgsql_proxy"
        - "--rpc_bind_addresses=yb-tserver-1:9100"
        - "--tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
      ports:
        - "127.0.0.1:5434:5433"
      depends_on:
        - yb-master-0
  yb-tserver-2:
      image: yugabytedb/yugabyte:2.6.18.0-b3
      command:
        - "/home/yugabyte/bin/yb-tserver"
        - "--fs_data_dirs=/mnt/tserver"
        - "--start_pgsql_proxy"
        - "--rpc_bind_addresses=yb-tserver-2:9100"
        - "--tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100"
      ports:
        - "127.0.0.1:5435:5433"
      depends_on:
        - yb-master-0

